driver:
  name: terraform
  root_module_directory: "test/test_fixture"

provisioner:
  name: terraform

verifier:
  name: awspec

platforms:
  - name: aws

suites:
  - name: default
    verifier:
      name: "awspec"
      patterns:
        - "test/integration/default/test_vpc.rb"
